services:
  webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://host.docker.internal:11434/api
    volumes:
      - ollama_webui:/data
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  ollama_webui:
